name: CustomItemCMD
main: BeeAZZ\CustomItemCMD\Main
version: 0.2
api: 4.0.0
author: BeeAZZ
description: Plugin Helps You Change Item Name And Description

commands:
 setitemname:
  description: "Change Name Item"
  permission: customitemcmd.command.setname
 setitemlore:
  description: "Change Lore Item"
  permission: customitemcmd.command.setlore

permissions:
  customitemcmd.command.setname:
    default: op
  customitemcmd.command.setlore:
    default: op
